#!/usr/bin/env sh

NPM_BIN=`npm bin`
NODEMON=$NPM_BIN/nodemon

EXAMPLE_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT=$( dirname $( dirname $EXAMPLE_ROOT ) )

# **Note** the `.nodemonignore` file is read from the directory you run `nodemon` from,
# not from the location of the node script you're running.
cd $EXAMPLE_ROOT
#echo $PWD

EXTS=node.js
APP=$EXAMPLE_ROOT/run.js

$NODEMON \
    -w $ROOT/common.blocks \
    -w $ROOT/app.blocks \
    -w $EXAMPLE_ROOT/common.blocks \
    -e $EXTS -d 1 $APP

exit 0

